export const GET_FACULTYS= "GET_FACULTYS"
export const DELETE_FACULTYS= "DELETE_FACULTYS"
export const ADD_FACULTYS= "ADD_FACULTYS"

export const GET_SEMESTERS= "GET_SEMESTERS"
export const DELETE_SEMESTERS= "DELETE_SEMESTERS"
export const ADD_SEMESTERS= "ADD_SEMESTERS"


export const GET_SUBJECTS= "GET_SUBJECTS"
export const DELETE_SUBJECTS= "DELETE_SUBJECTS"
export const ADD_SUBJECTS= "ADD_SUBJECTS"