export const GET_AUTHORS= "GET_AUTHORS"
export const DELETE_AUTHORS= "DELETE_AUTHORS"
export const ADD_AUTHORS= "ADD_AUTHORS"

export const GET_PUBLISHERS= "GET_PUBLISHERS"
export const DELETE_PUBLISHERS= "DELETE_PUBLISHERS"
export const ADD_PUBLISHERS= "ADD_PUBLISHERS"

export const GET_BOOKS= "GET_BOOKS"
export const DELETE_BOOKS= "DELETE_BOOKS"
export const ADD_BOOKS= "ADD_BOOKS"

export const GET_REQUESTS= "GET_REQUESTS"
export const DELETE_REQUESTS= "DELETE_REQUESTS"
export const ADD_REQUESTS= "ADD_REQUESTS"

export const GET_ISSUES= "GET_ISSUES"
export const DELETE_ISSUES= "DELETE_ISSUES"
export const ADD_ISSUES= "ADD_ISSUES"